name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I analyzed a driver and...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'kernel-watch analyze ...'
        2. See error...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of KernelWatch are you running?
      placeholder: v0.1.0
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
        - macOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      render: shell
